server:
  port: 8080

spring:
  devtools:
    add-properties: false
  config:
    activate:
      on-profile: reader
server.port: 8083

---
spring:
  config:
    activate:
      on-profile: writer
server.port: 8082


event-store:
  type: kafka
  kafka:
    bootstrap-servers: localhost:29092

  activemq:
    topic: cqrs_topic
